
name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: planty_test
          POSTGRES_USER: planty
          POSTGRES_PASSWORD: ""
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup DB
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: planty
        run: bin/rails db:setup
      - name: Test
        run: bin/rspec
